apiVersion: v1
kind: Service
metadata:
  name: backend-app
  namespace: uptoyoushop
spec:
  selector:
    app: uptoyoushop
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
