apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptoyoushop-postgresql-pvc
  labels:
    app: uptoyoushop
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: uptoyoushop-storage-class
  resources:
    requests:
      storage: 20Gi
