apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: uptoyoushop
  labels:
    app: uptoyoushop
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptoyoushop
  template:
    metadata:
      labels:
        app: uptoyoushop
    spec:
      containers:
        - name: backend-app
          image: maxdev888/uptoyoushop-backend:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              value: "postgres-primary.uptoyoushop.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            # - name: DB_NAME
            #   value: "uptoyoushop"
            # - name: DB_USER
            #   value: "uptoyoushop"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
