apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: uptoyoushop
    tier: backend
  namespace: uptoyoushop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptoyoushop
  template:
    metadata:
      labels:
        app: uptoyoushop
    spec:
      containers:
        - name: backend-app
          image: 575108951885.dkr.ecr.ap-southeast-1.amazonaws.com/uptoyoushop-backend:eb42aa1
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uptoyoushop-secret
                  key: POSTGRES_PASSWORD
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: uptoyoushop-secret
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: uptoyoushop-secret
                  key: STRIPE_WEBHOOK_SECRET
            - name: FRONTEND_URL
              value: "https://uptoyoushop.techallows.com"
            - name: CORS_ORIGIN
              value: "https://uptoyoushop.techallows.com"
            - name: DB_HOST
              value: "postgres-postgresql.uptoyoushop.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "uptoyoushop"
            - name: DB_USER
              value: "postgres"
            - name: JWT_SECRET
              value: "b72a6fb9515a62b0de7b12b3c886b5054e7da052da5f3100bc9199a0cf408ece"
            - name: DATABASE_URL
              value: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgres-postgresql:5432/uptoyoushop"
            - name: AWS_S3_PRODUCTS_BUCKET
              value: "uptoyoushop-product-bucket"
            - name: AWS_S3_CATEGORIES_BUCKET
              value: "uptoyoushop-category-bucket"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
