apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.7.x"
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: true
  values:
    clusterName: "uptoyou-eks-cluster"
    region: "ap-southeast-1"
    vpcId: "vpc-03b56c182c682f79e"
    serviceAccount:
      create: true
      name: aws-load-balancer-controller
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::575108951885:role/uptoyou-eks-cluster-aws-load-balancer-controller-role"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
