apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux-system # controllers, CRDs , GitRepository , Kustomization
  - ../../infrastructure # namespace / sealed-secrets / aws-load-balancer-controller
  - ../../app/overlays/production # Applications
  - ../../database # PostgreSQL
