apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux-system # controllers
  - infrastructure.yaml # namespace / sealed-secrets / aws-load-balancer-controller
  - external-secret.yaml
  - database.yaml # PostgreSQL
  - app.yaml # Applications
  - capacitor/capacitor.yaml # capacitor UI
