---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: uptoyoushop
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCyOoovHgqHwcgdlnZepymmY0pKivxZsaFKmxJ93haGwTe9XtR+V6/qxWL1H4kVxGjeUFlcG9BAX0D/yr5sxHrbNr1GWIYgxkY5sQlu9CEU190HuY8uoQuO/xj5kZBuZnpmoA+qUovTSQNm+cMwo3Bfsl4s4BNEiaj9EoJxEYwSpHHWgO2fnF+zB+WZ+PYnvBZSVHTk2LJpkZ9EH6CwM/4deFxUDEJAlCcDLpYDQaXIETlS1305qT/mGa5bhTCYRnAa4PNfRkff3y3yhLIFN+5ZOI2S1lRCz//FecgCadGMfkaiyKmEDpaifh3d/f84YF0j/cBgDzGt85pAEfK3TKB/SLLXVaaT6WlUfJHD72MoOQGk9kU1RTkxKFkNtzs547g58sruWLAzhp4mnoLt8PONOnKPnV+XgrcpxNpFE7eovnLRO+2rjofhMWbR0qkFsY6ujjqBl9li5oeOGK/pmTC/SFuwTG47ZmVG62/Jyv5SXSjIkunYytPgY+6pGz7ODiu+O/qiy0MVX0jqEJdQJ98j2coSKww6yH9qfiN6kaoxb3Dse054XMXWNDAv79uCSctPpopWeEZrZyxKG4PMKULWzq8aIrm+yJdPznvEAsmoDPZK6YH2LhluLKJgWrS/582iS0iAOirm1Fvre0829J0yQDbQ/rWW8zZA7NCGVJW2gXBUrvUTGmRgucuaC0HdhBY5KOKb
  template:
    metadata:
      name: postgres-secret
      namespace: uptoyoushop
