---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: uptoyoushop
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA+PMTWsf0i/DoC6m2hnUFtB8bE9hPTQpBas5BnptOTd7JcAbTiLB7YQ/3OxYc+JFwQK8zts78SXFiDZNrEIG6xLK6MihLAJ8QtRgTcGf8UR16Acbfzoyzp7W6U4GHf9QGde3YYewavmRyWUdWhnnAZ/k1tqqfGSiQ9Q9xc/uChg7Ng+SCWt0v4K2RPGlXF04bA+FXY25OvXTvOgIsEo7lKjtaGjrYcqwPR4nrtH41lQ8UT1tXtIQeWUqrE39IehpRJCph5hdGoxNu9bILF9bXxjwb0ogLmzCyOzICeVQMuPovabGSfw++yxFiMRikl4N7Ua27EBoIZv1uRdLrkv+5U3eibEO62Sgh3HG411KgLD6adD8IexamOQO9TzH55zeLjBaHVcbfFpqrrapQklqAIgbMhhlOn6aob+NlOtQKb2FW0gSsjfZtKKw1rGVzTk3c7NhSrddiCkJ2IwYpcMntgEpekotilGR+Pf/Mj1jU1QvbkreDm9jfnJKJf2ZeJVLxwxRngGUyCkR7yQ/R1o2vBuNC0OOJGr089m43Wd1bR6r46bHumybW3swC4HMyXANWEBWgP/MK24WsEsJd2sTj0Fbikb14b6GCN08C9Tlvmg2yT1WoR4wAwzZd+qcCoEWvvJXpc7HP2xyVZ3xFhinkGt4PEF3BOAiABKbCSP6n+ejLZ17E142UUzzHC1XR5pqIqyG4Z
  template:
    metadata:
      name: postgres-secret
      namespace: uptoyoushop
