---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: uptoyoushop
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCCMNcQlUReuBcSXqBohqqWtYu4vG8PeuBssAsFbA9gfC51nYJBToNm3gaDvqNM7GqmLSdjL0vmi/X5JJw37jdNnG9aJVF6v4hSuAT6hPnxm6k/L98/96o92AKMDSzqePQfmBRyLYzZ4vOJ1yHqFlhy4xJ8LTI78bcyW0tnZrIEgSF4UmXKt4Z2Kz5XYdhjBhzmOyvkrbUDEpJKaHgZOq3RRA5eL+GFprBjb2aaFGGBpDOm8lFWocOZoemyEieAqng/ofAJmfXF2m5XK08hTg78+IyK2nJQo7i42MqAXnZmwaPUCfXJoO3IKc3Ot59UJ4HMw/p4DrmB9Ki8ydc9IIBIqaqgXM4Vgc63Cik4pVwxxHSENh34xNV5i0kv+VrtbKt98jh0i9SwN9lUlGXyjdp4/LEPkaiEbOxyXAy66PNRu9dgVm8C2h7ANjNZXQZnWEBT/S3PZ5alFiFGxVEksJ+ewfsMmlfSmHptdJ6Ou4r7sbB4S8pZkbemGYoqTfOmmVJBFucF+K1xtp0uAny2a6CPXyHvQKPUggU8whyH8yFvf+nfCPCbYVe38KogamArLtq/0dhc6HEhV5hdvguEGYmp4z2vq81S5KnzhWeWrUZOVQ/QztdkA5132vCG0v1mrJOMZhs8LPLV61J3LDl/dhriSvSAkOuuzBPUDal3KZQJCIDdGyg0VCwVQdThPt+WTizlR/UH
  template:
    metadata:
      name: postgres-secret
      namespace: uptoyoushop
