apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: uptoyoushop
  labels:
    release: prometheus # ให้ตรงกับ Helm release label เพื่อให้ Operator ค้นพบ
spec:
  selector:
    matchLabels:
      app: backend-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
