apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptoyoushop-ingress
  namespace: uptoyoushop
  labels:
    app: uptoyoushop
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-app
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-app
                port:
                  number: 80
  
