apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-community
  namespace: observability
spec:
  interval: 1m0s
  url: https://grafana-community.github.io/helm-charts
