apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stripe-secret
  namespace: uptoyoushop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: stripe-secret
    creationPolicy: Owner
  data:
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: stripe/uptoyou
        property: STRIPE_SECRET_KEY
    - secretKey: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      remoteRef:
        key: stripe/uptoyou
        property: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: stripe/uptoyou
        property: STRIPE_WEBHOOK_SECRET