apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: uptoyoushop
spec:
  interval: 1h
  chart:
    spec:
      chart: external-secrets
      version: ">=0.13.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: uptoyoushop
  dependsOn:
    - name: aws-load-balancer-controller
      namespace: flux-system
  install:
    createNamespace: true
  values:
    serviceAccount:
      create: true
      name: external-secrets
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::575108951885:role/uptoyou-eks-cluster-external-secrets-role"
        # eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/${var.cluster_name}-external-secrets-role