apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: uptoyoushop-secret
  namespace: uptoyoushop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: uptoyoushop-secret
    creationPolicy: Owner
  data:
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: stripe/uptoyoushop
        property: STRIPE_SECRET_KEY
    - secretKey: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      remoteRef:
        key: stripe/uptoyoushop
        property: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: stripe/uptoyoushop
        property: STRIPE_WEBHOOK_SECRET
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres/uptoyoushop
        property: POSTGRES_PASSWORD