# PostgreSQL values for EKS deployment
global:
  storageClass: "gp3" #ต้องติดตั้ง EBS CSI Driver บน EKS ก่อน ไม่งั้น gp3 ใช้ไม่ได้
  postgresql:
    auth:
      # postgresPassword: "YOUR_POSTGRES_PASSWORD_HERE"
      username: "postgres"
      password: "YOUR_POSTGRES_PASSWORD_HERE"
      database: "uptoyoushop"

primary:
  name: postgres-primary
  size: 2
  persistence:
    enabled: true
    storageClass: "gp3"
    size: 20Gi
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  extraEnvVars:
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata

readReplicas:
  name: postgres-replica
  replicaCount: 3
  size: 2

  persistence:
    enabled: true
    storageClass: "gp3"
    size: 20Gi
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

metrics:
  # Disable Prometheus metrics for now
  enabled: false
  serviceMonitor:
    enabled: false
    namespace: uptoyoushop

# backup:
#   enabled: true
#   schedule: "0 2 * * *" # Daily at 2 AM
#   retention: "7d"

# Service configuration
service:
  type: ClusterIP
  port: 5432

networkPolicy:
  enabled: true

# EKS specific configurations
rbac:
  create: true

serviceAccount:
  create: true
  name: postgres
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::ACCOUNT:role/postgres-role"
