apiVersion: v1
kind: ServiceAccount
metadata:
  name: ses-sa
  namespace: default
  annotations:
    # Replace with the output value: terraform output -raw ses_service_account_role_arn
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/uptoyou-eks-cluster-ses-role
