apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - controllers/aws-load-balancer-controller/
  - controllers/external-secrets-operator/
  # - controllers/sealed-secrets/
  # - controllers/ses/
  - configs/
